apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: pubsub-app-subscriber
  namespace: test
spec:
  # member: serviceAccount:pubsub-app@[PROJECT_ID].iam.gserviceaccount.com
  member: serviceAccount:pubsub-app@jerome-config-connector-test.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: echo
