apiVersion: v1
kind: ServiceAccount
metadata:
  name: pubsub
  namespace: test
  annotations:
      # iam.gke.io/gcp-service-account: GSA_NAME@PROJECT_ID.iam.gserviceaccount.com
      iam.gke.io/gcp-service-account: pubsub-app@jerome-config-connector-test.iam.gserviceaccount.com
